from enum import Enum


class MessageType(str, Enum):
    TEXT = "TYPE_TEXT"
    TABLE = "TYPE_TABLE"
    GRAPH = "TYPE_GRAPH"
    SUMMARY = "TYPE_SUMMARY"
    STATUS = "TYPE_STATUS"
    ERROR = "TYPE_ERROR"
    PING = "TYPE_PING"
    PONG = "TYPE_PONG"
    SUGGESTED_QUESTIONS = "TYPE_SUGGESTED_QUESTIONS"
